---
title: "clrtap-gridded-review"
author: "Christopher Evangelides"
date: "24/04/2324"
output: pdf_document
---

```{r setup_R, warning=FALSE}
# library(ggplot2)
# library(tidyverse)
# library(officer)
# library(here)
# library(odbc)
# library(dbplyr)
# library(janitor)
# library(stringr)
library(readxl)
# library(sf)
# library(DBI)
# library(RPostgres)
# library(purrr)
library(RPostgreSQL)
library(dplyr)
# library(here)
# library(RODBC)
```    

# 1. Setup

```{r setup_docs}
source("./pg_gisdata_connect.R")
source("./parameters.R")
```

```{r create_schema}
dbExecute(conn, paste0("CREATE SCHEMA clrtap;"))
dbExecute(conn, paste0("GRANT ALL PRIVILEGES ON SCHEMA clrtap TO PUBLIC;"))
```

# 2. Load data

Load data from country reports (EMEP) and CAMS.

# 2.1 CAMS

```{r}
NMVOC_2015_E_Solvents_EMEP <- read.csv("Q:/Delivery/GISdata/CLRTAP/data/CAMS_at _EMEP_grids/CAMS_v5161_NMVOC_2015_E_Solvents_EMEP.csv")

NMVOC_2019_E_Solvents_EMEP <- read.csv("Q:/Delivery/GISdata/CLRTAP/data/CAMS_at _EMEP_grids/CAMS_v5161_NMVOC_2019_E_Solvents_EMEP.csv")

NMVOC_2020_E_Solvents_EMEP <- read.csv("Q:/Delivery/GISdata/CLRTAP/data/CAMS_at _EMEP_grids/CAMS_v5161_NMVOC_2020_E_Solvents_EMEP.csv")
```

```{r}
# For NMVOC_2020_E_Solvents_EMEP dataframe
NMVOC_2020_E_Solvents_EMEP <- NMVOC_2020_E_Solvents_EMEP %>%
  mutate(x = x / 100,
         y = y / 100) %>%
  rename(emission_t = emission)

# For NMVOC_2019_E_Solvents_EMEP dataframe
NMVOC_2019_E_Solvents_EMEP <- NMVOC_2019_E_Solvents_EMEP %>%
  mutate(x = x / 100,
         y = y / 100) %>%
  rename(emission_t = emission)

# For NMVOC_2015_E_Solvents_EMEP dataframe
NMVOC_2015_E_Solvents_EMEP <- NMVOC_2015_E_Solvents_EMEP %>%
  mutate(x = x / 100,
         y = y / 100) %>%
  rename(emission_t = emission)

```

# 2.1.1 CAMS to postgres
```{r}
dbExecute(conn, paste0("DROP TABLE IF EXISTS clrtap.cams_nmvoc_2015_e_solvents;"))
dbWriteTable(conn, Id(schema = 'clrtap', table = "cams_nmvoc_2015_e_solvents"), value = NMVOC_2015_E_Solvents_EMEP)
dbExecute(conn, paste0("DROP TABLE IF EXISTS clrtap.cams_nmvoc_2019_e_solvents;"))
dbWriteTable(conn, Id(schema = 'clrtap', table = "cams_nmvoc_2019_e_solvents"), value = NMVOC_2019_E_Solvents_EMEP)
dbExecute(conn, paste0("DROP TABLE IF EXISTS clrtap.cams_nmvoc_2020_e_solvents;"))
dbWriteTable(conn, Id(schema = 'clrtap', table = "cams_nmvoc_2020_e_solvents"), value = NMVOC_2020_E_Solvents_EMEP)

```

# 2.1.2 Add geom

```{r}
# For clrtap.cams_nmvoc_2020_e_solvents table
dbExecute(conn, paste0("ALTER TABLE clrtap.cams_nmvoc_2020_e_solvents
                       ADD COLUMN geom geometry(Point, 4326);"));

# Index x and y columns
dbExecute(conn, paste0("CREATE INDEX idx_cams_nmvoc_2020_e_solvents_x ON clrtap.cams_nmvoc_2020_e_solvents (x);"));
dbExecute(conn, paste0("CREATE INDEX idx_cams_nmvoc_2020_e_solvents_y ON clrtap.cams_nmvoc_2020_e_solvents (y);"));

dbExecute(conn, paste0("UPDATE clrtap.cams_nmvoc_2020_e_solvents SET geom = ST_SetSRID(ST_MakePoint(x, y), 4326);"));

# Add spatial index
dbExecute(conn, paste0("CREATE INDEX idx_cams_nmvoc_2020_e_solvents_geom ON clrtap.cams_nmvoc_2020_e_solvents USING GIST(geom);"));

# Repeat for clrtap.cams_nmvoc_2019_e_solvents table
dbExecute(conn, paste0("ALTER TABLE clrtap.cams_nmvoc_2019_e_solvents 
                       ADD COLUMN geom geometry(Point, 4326);"));

dbExecute(conn, paste0("CREATE INDEX idx_cams_nmvoc_2019_e_solvents_x ON clrtap.cams_nmvoc_2019_e_solvents (x);"));
dbExecute(conn, paste0("CREATE INDEX idx_cams_nmvoc_2019_e_solvents_y ON clrtap.cams_nmvoc_2019_e_solvents (y);"));

dbExecute(conn, paste0("UPDATE clrtap.cams_nmvoc_2019_e_solvents 
                       SET geom = ST_SetSRID(ST_MakePoint(x, y), 4326);"));

dbExecute(conn, paste0("CREATE INDEX idx_cams_nmvoc_2019_e_solvents_geom ON clrtap.cams_nmvoc_2019_e_solvents USING GIST(geom);"));

# Repeat for clrtap.cams_nmvoc_2015_e_solvents table
dbExecute(conn, paste0("ALTER TABLE clrtap.cams_nmvoc_2015_e_solvents 
                       ADD COLUMN geom geometry(Point, 4326);"));

dbExecute(conn, paste0("CREATE INDEX idx_cams_nmvoc_2015_e_solvents_x ON clrtap.cams_nmvoc_2015_e_solvents (x);"));
dbExecute(conn, paste0("CREATE INDEX idx_cams_nmvoc_2015_e_solvents_y ON clrtap.cams_nmvoc_2015_e_solvents (y);"));

dbExecute(conn, paste0("UPDATE clrtap.cams_nmvoc_2015_e_solvents SET geom = ST_SetSRID(ST_MakePoint(x, y), 4326);"));

dbExecute(conn, paste0("CREATE INDEX idx_cams_nmvoc_2015_e_solvents_geom ON clrtap.cams_nmvoc_2015_e_solvents USING GIST(geom);"));






```

# 2.2 Reported data

```{r}
Reported_NMVOC_E_Solvents <- read.csv("Q:/Delivery/GISdata/CLRTAP/data/EMEP_gridded_data_allSources/NMVOC/Rep_GRID_NMVOC.csv")

Reported_NMVOC_E_Solvents <- Reported_NMVOC_E_Solvents %>%
  mutate(x = x / 100,
         y = y / 100) %>%
  rename(emission_t = emission)

```

```{r}

Reported_NMVOC_2020_E_Solvents <- Reported_NMVOC_E_Solvents[Reported_NMVOC_E_Solvents$year == 2020, ]
Reported_NMVOC_2019_E_Solvents <- Reported_NMVOC_E_Solvents[Reported_NMVOC_E_Solvents$year == 2019, ]
Reported_NMVOC_2015_E_Solvents <- Reported_NMVOC_E_Solvents[Reported_NMVOC_E_Solvents$year == 2015, ]

rm(Reported_NMVOC_E_Solvents)
```

  # 2.2.1 Reported to postgres
```{r}
dbExecute(conn, paste0("DROP TABLE IF EXISTS clrtap.reported_nmvoc_2015_e_solvents;"))
dbWriteTable(conn, Id(schema = 'clrtap', table = "reported_nmvoc_2015_e_solvents"), value = Reported_NMVOC_2015_E_Solvents)
dbExecute(conn, paste0("DROP TABLE IF EXISTS clrtap.reported_nmvoc_2019_e_solvents;"))
dbWriteTable(conn, Id(schema = 'clrtap', table = "reported_nmvoc_2019_e_solvents"), value = Reported_NMVOC_2019_E_Solvents)
dbExecute(conn, paste0("DROP TABLE IF EXISTS clrtap.reported_nmvoc_2020_e_solvents;"))
dbWriteTable(conn, Id(schema = 'clrtap', table = "reported_nmvoc_2020_e_solvents"), value = Reported_NMVOC_2020_E_Solvents)

```



# 2.2.2 Add geom

```{r}
# For clrtap.reported_nmvoc_2020_e_solvents table
dbExecute(conn, paste0("ALTER TABLE clrtap.reported_nmvoc_2020_e_solvents
                       ADD COLUMN geom geometry(Point, 4326);"));

# Index x and y columns
dbExecute(conn, paste0("CREATE INDEX idx_reported_nmvoc_2020_e_solvents_x ON clrtap.reported_nmvoc_2020_e_solvents (x);"));
dbExecute(conn, paste0("CREATE INDEX idx_reported_nmvoc_2020_e_solvents_y ON clrtap.reported_nmvoc_2020_e_solvents (y);"));

dbExecute(conn, paste0("UPDATE clrtap.reported_nmvoc_2020_e_solvents SET geom = ST_SetSRID(ST_MakePoint(x, y), 4326);"));

# Add spatial index
dbExecute(conn, paste0("CREATE INDEX idx_reported_nmvoc_2020_e_solvents_geom ON clrtap.reported_nmvoc_2020_e_solvents USING GIST(geom);"));

# Repeat for clrtap.reported_nmvoc_2019_e_solvents table
dbExecute(conn, paste0("ALTER TABLE clrtap.reported_nmvoc_2019_e_solvents 
                       ADD COLUMN geom geometry(Point, 4326);"));

dbExecute(conn, paste0("CREATE INDEX idx_reported_nmvoc_2019_e_solvents_x ON clrtap.reported_nmvoc_2019_e_solvents (x);"));
dbExecute(conn, paste0("CREATE INDEX idx_reported_nmvoc_2019_e_solvents_y ON clrtap.reported_nmvoc_2019_e_solvents (y);"));

dbExecute(conn, paste0("UPDATE clrtap.reported_nmvoc_2019_e_solvents 
                       SET geom = ST_SetSRID(ST_MakePoint(x, y), 4326);"));

dbExecute(conn, paste0("CREATE INDEX idx_reported_nmvoc_2019_e_solvents_geom ON clrtap.reported_nmvoc_2019_e_solvents USING GIST(geom);"));

# Repeat for clrtap.reported_nmvoc_2015_e_solvents table
dbExecute(conn, paste0("ALTER TABLE clrtap.reported_nmvoc_2015_e_solvents 
                       ADD COLUMN geom geometry(Point, 4326);"));

dbExecute(conn, paste0("CREATE INDEX idx_reported_nmvoc_2015_e_solvents_x ON clrtap.reported_nmvoc_2015_e_solvents (x);"));
dbExecute(conn, paste0("CREATE INDEX idx_reported_nmvoc_2015_e_solvents_y ON clrtap.reported_nmvoc_2015_e_solvents (y);"));

dbExecute(conn, paste0("UPDATE clrtap.reported_nmvoc_2015_e_solvents SET geom = ST_SetSRID(ST_MakePoint(x, y), 4326);"));

dbExecute(conn, paste0("CREATE INDEX idx_reported_nmvoc_2015_e_solvents_geom ON clrtap.reported_nmvoc_2015_e_solvents USING GIST(geom);"));

```



# 3. Clean dataset

Remove unwanted years from CAMS' datasets

```{r}

dbExecute(conn, paste0("DELETE FROM clrtap.cams_nmvoc_2015_e_solvents
                        WHERE \"ISO2\" NOT IN ('RO', 'GE')"));
dbExecute(conn, paste0("DELETE FROM clrtap.cams_nmvoc_2019_e_solvents
                        WHERE \"ISO2\"  IN ('RO', 'GE', 'RS', 'FI')"));
dbExecute(conn, paste0("DELETE FROM clrtap.cams_nmvoc_2020_e_solvents
                        WHERE \"ISO2\" NOT IN ('RS', 'FI')"));

dbExecute(conn, paste0("ALTER TABLE clrtap.cams_nmvoc_2015_e_solvents 
                        ADD COLUMN year INTEGER DEFAULT 2015"));
dbExecute(conn, paste0("ALTER TABLE clrtap.cams_nmvoc_2019_e_solvents 
                        ADD COLUMN year INTEGER DEFAULT 2019"));
dbExecute(conn, paste0("ALTER TABLE clrtap.cams_nmvoc_2020_e_solvents 
                        ADD COLUMN year INTEGER DEFAULT 2020"));


```


# 4. Merge tables

Merge tables so we will have 1 for CAMS and 1 for Reported

```{r}
# CAMS

dbExecute(conn, paste0("DROP TABLE IF EXISTS clrtap.cams_nmvoc_e_solvents;"))
dbExecute(conn, paste0("CREATE TABLE clrtap.cams_nmvoc_e_solvents as 
                        SELECT * FROM clrtap.cams_nmvoc_2015_e_solvents
                       UNION
                        SELECT * FROM clrtap.cams_nmvoc_2019_e_solvents
                       UNION
                        SELECT * FROM clrtap.cams_nmvoc_2020_e_solvents;"))

dbExecute(conn, paste0("CREATE INDEX idx_cams_nmvoc_e_solvents_ISO2 ON clrtap.cams_nmvoc_e_solvents (\"ISO2\");"));
dbExecute(conn, paste0("CREATE INDEX idx_cams_nmvoc_e_solvents_emission_t ON clrtap.cams_nmvoc_e_solvents (emission_t);"));
dbExecute(conn, paste0("CREATE INDEX idx_cams_nmvoc_e_solvents_year ON clrtap.cams_nmvoc_e_solvents (year);"));

# Reported

dbExecute(conn, paste0("DROP TABLE IF EXISTS clrtap.reported_nmvoc_e_solvents;"))
dbExecute(conn, paste0("CREATE TABLE clrtap.reported_nmvoc_e_solvents as 
                        SELECT * FROM clrtap.reported_nmvoc_2015_e_solvents
                       UNION
                        SELECT * FROM clrtap.reported_nmvoc_2019_e_solvents
                       UNION
                        SELECT * FROM clrtap.reported_nmvoc_2020_e_solvents;"))

dbExecute(conn, paste0("CREATE INDEX idx_reported_nmvoc_e_solvents_ISO2 ON clrtap.reported_nmvoc_e_solvents (\"ISO2\");"));
dbExecute(conn, paste0("CREATE INDEX idx_reported_nmvoc_e_solvents_emission_t ON clrtap.reported_nmvoc_e_solvents (emission_t);"));
dbExecute(conn, paste0("CREATE INDEX idx_reported_nmvoc_e_solvents_year ON clrtap.reported_nmvoc_e_solvents (year);"));


``` 